# Generated by Django 4.2.6 on 2023-10-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Provide the name of the product', max_length=100, verbose_name='name')),
                ('price', models.CharField(help_text='Provide the price of the product', max_length=100, verbose_name='price')),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('black', 'Black'), ('orange', 'Orange'), ('white', 'White')], max_length=10, verbose_name='color')),
                ('size', models.CharField(choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=10, verbose_name='size')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
