# Generated by Django 4.2.6 on 2023-11-14 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
    ]
