# Generated by Django 4.2.6 on 2023-11-15 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='size',
        ),
    ]
