# Generated by Django 4.2.6 on 2023-10-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagem',
            field=models.ImageField(default=1, upload_to='files'),
            preserve_default=False,
        ),
    ]
