# Generated by Django 4.2.6 on 2023-12-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_options_product_color_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estoque',
            field=models.IntegerField(default=1, verbose_name='estoque atual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='estoque mínimo'),
        ),
    ]
