# Generated by Django 4.2.6 on 2023-10-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imagem',
            new_name='image',
        ),
    ]
