# Generated by Django 4.2.6 on 2023-10-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_imagem_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='files/products/<built-in function id>/'),
        ),
    ]
