# Generated by Django 4.2.6 on 2023-12-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_estoque_product_estoque_minimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='estoque_minimo',
        ),
        migrations.AlterField(
            model_name='product',
            name='estoque',
            field=models.IntegerField(default=0, verbose_name='estoque atual'),
        ),
    ]
