# Generated by Django 4.2.6 on 2023-10-29 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image'),
        ('product', '0007_alter_product_image'),
    ]

    operations = [
    ]
