# Generated by Django 4.2.6 on 2023-10-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.size'),
            preserve_default=False,
        ),
    ]
